version: '3.6'
services:
  nginx:
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    volumes:
      - ./:/var/www/html
      - ./conf/php.conf:/etc/php/7.2/pool.d/www.conf

  pgsql:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=application_db
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      - agilize

  mysql:
    image: mysql:8.0.21-1.1.17
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - agilize

  rabbitmq:
    image: rabbitmq:3.6.10-management
    volumes:
      - ./conf/rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - agilize

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local