version: '3.6'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 1112:80
    networks:
      - agilize
  php:
    build:
      context: .
    restart: always
    dns:
      - 8.8.8.8
    networks:
      - agilize
networks:
  agilize:
    name: agilize
    driver: bridge