version: '3.6'
services:
  nginx:
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    volumes:
      - ./:/var/www/html
      - ./conf/php.conf:/etc/php/7.2/pool.d/www.conf